version: '3.3'
services:

  db:
    image: "sqlite"
    volumes:
      - db_volume2:/app/db/
    restart: always
    env_file:
      - ./.env

  backend:
    image: "stripeback:latest"
    restart: always
    volumes:
      - static_volume:/app/static/
      # - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      # - media_volume:/var/html/media/
    depends_on:
      - backend


volumes:
  static_volume:
  # media_volume:
  db_volume2: